use crate::{
    endpoints::book::*,
    filters::{book_service, pagination},
};
use std::net::SocketAddr;
use uuid::Uuid;
use warp::{filters::BoxedFilter, Filter, Reply};

pub fn book(book_addr: SocketAddr) -> BoxedFilter<(impl Reply,)> {
    warp::path("book")
        .and(
            // GET /book
            warp::path::end()
                .and(book_service(book_addr))
                .and(pagination::pagination())
                .and(warp::get())
                .and_then(get_books)
                .boxed()
                // GET /book/{book_id}
                .or(warp::path::param::<Uuid>()
                    .and(warp::path::end())
                    .and(book_service(book_addr))
                    .and(warp::get())
                    .and_then(get_book_by_id)
                    .boxed())
                // GET /book/{book_id}/authors
                .or(warp::path::param::<Uuid>()
                    .and(warp::path("authors"))
                    .and(warp::path::end())
                    .and(book_service(book_addr))
                    .and(pagination::pagination())
                    .and(warp::get())
                    .and_then(get_authors_by_book_id)
                    .boxed())
                // GET /book/{book_id}/category
                .or(warp::path::param::<Uuid>()
                    .and(warp::path("category"))
                    .and(warp::path::end())
                    .and(book_service(book_addr))
                    .and(warp::get())
                    .and_then(get_category_by_book_id)
                    .boxed())
                // GET /book/{book_id}/copies
                .or(warp::path::param::<Uuid>()
                    .and(warp::path("copies"))
                    .and(warp::path::end())
                    .and(book_service(book_addr))
                    .and(pagination::pagination())
                    .and(warp::get())
                    .and_then(get_copies_by_book_id)
                    .boxed())
                // GET /book/{book_id}/editors
                .or(warp::path::param::<Uuid>()
                    .and(warp::path("editors"))
                    .and(warp::path::end())
                    .and(book_service(book_addr))
                    .and(pagination::pagination())
                    .and(warp::get())
                    .and_then(get_editors_by_book_id)
                    .boxed())
                // GET /book/{book_id}/language
                .or(warp::path::param::<Uuid>()
                    .and(warp::path("language"))
                    .and(warp::path::end())
                    .and(book_service(book_addr))
                    .and(warp::get())
                    .and_then(get_language_by_book_id)
                    .boxed())
                // GET /book/{book_id}/publisher
                .or(warp::path::param::<Uuid>()
                    .and(warp::path("publisher"))
                    .and(warp::path::end())
                    .and(book_service(book_addr))
                    .and(warp::get())
                    .and_then(get_publisher_by_book_id)
                    .boxed())
                // GET /book/{book_id}/series
                .or(warp::path::param::<Uuid>()
                    .and(warp::path("series"))
                    .and(warp::path::end())
                    .and(book_service(book_addr))
                    .and(warp::get())
                    .and_then(get_series_by_book_id)
                    .boxed())
                // GET /book/{book_id}/subject_areas
                .or(warp::path::param::<Uuid>()
                    .and(warp::path("subject_areas"))
                    .and(warp::path::end())
                    .and(book_service(book_addr))
                    .and(pagination::pagination())
                    .and(warp::get())
                    .and_then(get_subject_areas_by_book_id)
                    .boxed())
                // GET /book/{book_id}/tags
                .or(warp::path::param::<Uuid>()
                    .and(warp::path("tags"))
                    .and(warp::path::end())
                    .and(book_service(book_addr))
                    .and(pagination::pagination())
                    .and(warp::get())
                    .and_then(get_tags_by_book_id)
                    .boxed())
                // GET /book/authors
                .or(warp::path("authors")
                    .and(warp::path::end())
                    .and(book_service(book_addr))
                    .and(pagination::pagination())
                    .and(warp::get())
                    .and_then(get_authors)
                    .boxed())
                // GET /book/authors/author_id
                .or(warp::path("authors")
                    .and(warp::path::param::<Uuid>())
                    .and(warp::path::end())
                    .and(book_service(book_addr))
                    .and(warp::get())
                    .and_then(get_author_by_id)
                    .boxed())
                // GET /book/categories
                .or(warp::path("categories")
                    .and(warp::path::end())
                    .and(book_service(book_addr))
                    .and(pagination::pagination())
                    .and(warp::get())
                    .and_then(get_categories)
                    .boxed())
                // GET /book/categories/{category_id}
                .or(warp::path("categories")
                    .and(warp::path::param::<Uuid>())
                    .and(warp::path::end())
                    .and(book_service(book_addr))
                    .and(warp::get())
                    .and_then(get_category_by_id)
                    .boxed())
                // GET /book/copies
                .or(warp::path("copies")
                    .and(warp::path::end())
                    .and(book_service(book_addr))
                    .and(pagination::pagination())
                    .and(warp::get())
                    .and_then(get_copies)
                    .boxed())
                // GET /book/copies/{copy_id}
                .or(warp::path("copies")
                    .and(warp::path::param::<Uuid>())
                    .and(warp::path::end())
                    .and(book_service(book_addr))
                    .and(warp::get())
                    .and_then(get_copy_by_id)
                    .boxed())
                // GET /book/editors
                .or(warp::path("editors")
                    .and(warp::path::end())
                    .and(book_service(book_addr))
                    .and(pagination::pagination())
                    .and(warp::get())
                    .and_then(get_editors)
                    .boxed())
                // GET /book/editors/{editor_id}
                .or(warp::path("editors")
                    .and(warp::path::param::<Uuid>())
                    .and(warp::path::end())
                    .and(book_service(book_addr))
                    .and(warp::get())
                    .and_then(get_editor_by_id)
                    .boxed())
                // GET /book/languages
                .or(warp::path("languages")
                    .and(warp::path::end())
                    .and(book_service(book_addr))
                    .and(pagination::pagination())
                    .and(warp::get())
                    .and_then(get_languages)
                    .boxed())
                // GET /book/languages/{language_id}
                .or(warp::path("languages")
                    .and(warp::path::param::<Uuid>())
                    .and(warp::path::end())
                    .and(book_service(book_addr))
                    .and(warp::get())
                    .and_then(get_language_by_id)
                    .boxed())
                // GET /book/publishers
                .or(warp::path("publishers")
                    .and(warp::path::end())
                    .and(book_service(book_addr))
                    .and(pagination::pagination())
                    .and(warp::get())
                    .and_then(get_publishers)
                    .boxed())
                // GET /book/publishers/{publisher_id}
                .or(warp::path("publisher")
                    .and(warp::path::param::<Uuid>())
                    .and(warp::path::end())
                    .and(book_service(book_addr))
                    .and(warp::get())
                    .and_then(get_publisher_by_id)
                    .boxed())
                // GET /book/series
                .or(warp::path("series")
                    .and(warp::path::end())
                    .and(book_service(book_addr))
                    .and(pagination::pagination())
                    .and(warp::get())
                    .and_then(get_series)
                    .boxed())
                // GET /book/series/{series_id}
                .or(warp::path("series")
                    .and(warp::path::param::<Uuid>())
                    .and(warp::path::end())
                    .and(book_service(book_addr))
                    .and(warp::get())
                    .and_then(get_series_by_id)
                    .boxed())
                // GET /book/subject_areas
                .or(warp::path("subject_areas")
                    .and(warp::path::end())
                    .and(book_service(book_addr))
                    .and(pagination::pagination())
                    .and(warp::get())
                    .and_then(get_subject_areas)
                    .boxed())
                // GET /book/subject_areas/{subject_area_id}
                .or(warp::path("subject_areas")
                    .and(warp::path::param::<Uuid>())
                    .and(warp::path::end())
                    .and(book_service(book_addr))
                    .and(warp::get())
                    .and_then(get_subject_area_by_id)
                    .boxed())
                // GET /book/tags
                .or(warp::path("tags")
                    .and(warp::path::end())
                    .and(book_service(book_addr))
                    .and(pagination::pagination())
                    .and(warp::get())
                    .and_then(get_tags)
                    .boxed())
                // GET /book/tags/{tag_id}
                .or(warp::path("tags")
                    .and(warp::path::param::<Uuid>())
                    .and(warp::path::end())
                    .and(book_service(book_addr))
                    .and(warp::get())
                    .and_then(get_tag_by_id)
                    .boxed()),
        )
        .boxed()
}
