on:
    push:
        branches:
            - "master"
        paths:
            - "api/**"
            - "Cargo.lock"
            - "**/cd-dev-api.yml"

jobs:
    build_deploy:
        runs-on: ubuntu-latest

        env:
            SERVICE_NAME: api
            REPOSITORY: ${{ secrets.AWS_ECR_REGISTRY }}
            IMAGE_TAG: latest-dev

        steps:
            - uses: actions/checkout@v2

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: eu-central-1
            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Build Docker image
              run: docker build -t $REPOSITORY/code-library-$SERVICE_NAME:$IMAGE_TAG -f $SERVICE_NAME/Dockerfile .
            - name: Push Docker image
              run: docker push $REPOSITORY/code-library-$SERVICE_NAME:$IMAGE_TAG
