name: CI
on:
  push:
    branches-ignore:
      - 'master'

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: 'Install Rust toolchain'
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: 'Set PATH variable'
        run: source $HOME/.cargo/env
      - name: 'Fetch source code from repository'
        uses: actions/checkout@v2
      - name: 'Run format check'
        run: cargo fmt -- --check
  dependencies:
    name: Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: 'Install Rust toolchain'
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: 'Set PATH variable'
        run: source $HOME/.cargo/env
      - name: 'Fetch source code from repository'
        uses: actions/checkout@v2
      - name: 'Run package check'
        run: cargo check --all-targets --all-features
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: 'Install Rust toolchain'
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: 'Set PATH variable'
        run: source $HOME/.cargo/env
      - name: 'Fetch source code from repository'
        uses: actions/checkout@v2
      - name: 'Run linter check'
        run: cargo clippy --all-targets --all-features -- -D warnings
  unittest:
    name: Unittest
    runs-on: ubuntu-latest
    steps:
      - name: 'Install Rust toolchain'
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: 'Set PATH variable'
        run: source $HOME/.cargo/env
      - name: 'Fetch source code from repository'
        uses: actions/checkout@v2
      - name: 'Run unit tests'
        run: cargo test --all-targets --all-features
