on:
    push:
        branches-ignore:
            - 'master'

jobs:
    ci:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                rust: [stable, beta]
                conf: [fmt, clippy, check, test]
                experimental: [true, false]
                exclude:
                    - rust: stable
                      experimental: true
                    - rust: beta
                      experimental: false
        continue-on-error: ${{ matrix.experimental }}
        steps:
            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  components: rustfmt, clippy
                  override: true
                  profile: minimal
                  toolchain: ${{ matrix.rust }}

            - uses: actions/checkout@v2

            - if: matrix.conf == 'fmt'
              run: cargo fmt -- --check
            - if: matrix.conf == 'clippy'
              run: cargo clippy --all-targets --all-features -- -D warnings
            - if: matrix.conf == 'check'
              run: cargo check --all-targets --all-features
            - if: matrix.conf == 'test'
              run: cargo test --all-targets --all-features
